version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development  # Default to dev mode
    ports:
      - "5173:5173"  # Vite dev server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
