version: "3.8"

services:
  backend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo:27017/mydb"
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydb

volumes:
  mongo_data:
